env:
  TERM: xterm-256color

window:
  decorations: Buttonless
  # opacity: 0.8
  # blur: true
  padding:
    x: 20
    y: 20
  startup_mode: Maximized
  opt_as_alt: Both

use_thin_strokes: true

font:
  size: 18
  normal:
    family: "MesloLGS Nerd Font"
    style: Regular

  bold:
    family: "MesloLGS Nerd Font"
    style: Bold

  italic:
    family: "MesloLGS Nerd Font"
    style: Light

colors:
  primary:
    background: "#121212"
    foreground: "#d0d0d0"
    # dim_foreground: "#c5c8c6"
    dim_foreground: "#4e4e4e"
    bright_foreground: "#F2F3F4"

  normal:
    black: "#111111"
    red: "#D75F5F"
    green: "#5F8787"
    yellow: "#DFAF5F"
    blue: "#5F87AF"
    magenta: "#AF8787"
    cyan: "#87AFAF"
    white: "#BFBFBF"

  bright:
    black: "#3a3a3a"
    red: "#D75F5F"
    green: "#5F8787"
    yellow: "#DFAF5F"
    blue: "#5F87AF"
    magenta: "#AF8787"
    cyan: "#87AFAF"
    white: "#E5E5E5"
