env:
  TERM: xterm-256color

window:
  decorations: Buttonless
  opacity: 1
  padding:
    x: 20
    y: 20
  startup_mode: Maximized
  opt_as_alt: Both

use_thin_strokes: true

font:
  size: 18
  normal:
    family: "Hack Nerd Font"
    style: Regular

colors:
  # Default colors
  primary:
    background: "#0A0E14"
    foreground: "#B3B1AD"

  # Normal colors
  normal:
    black: "#01060E"
    red: "#EA6C73"
    green: "#91B362"
    yellow: "#F9AF4F"
    blue: "#53BDFA"
    magenta: "#FAE994"
    cyan: "#90E1C6"
    white: "#C7C7C7"

  # Bright colors
  bright:
    black: "#686868"
    red: "#F07178"
    green: "#C2D94C"
    yellow: "#FFB454"
    blue: "#59C2FF"
    magenta: "#FFEE99"
    cyan: "#95E6CB"
    white: "#FFFFFF"
theme: Ayu-Dark
