window:
  decorations: "buttonless"
  padding:
    x: 10
    y: 10

  use_thin_strokes: true

font:
  normal:
    family: "JetBrainsMono Nerd Font Mono"
    style: Regular
    size: 20 

schemes:
  everforest_dark_hard: &everforest_dark_hard
    primary:
      background: "#2b3339"
      foreground: "#d3c6aa"
    normal:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
    bright:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
  everforest_dark_medium: &everforest_dark_medium
    primary:
      background: "#2f383e"
      foreground: "#d3c6aa"
    normal:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
    bright:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
  everforest_dark_soft: &everforest_dark_soft
    primary:
      background: "#323d43"
      foreground: "#d3c6aa"
    normal:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
    bright:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
  gruvbox: &gruvbox
    primary:
      # hard contrast:
      background: "0x1d2021"
      # background: '0x282828'
      # soft contrast: background = '0x32302f'
      foreground: "0xebdbb2"

    # Normal colors
    normal:
      black: "0x282828"
      red: "0xcc241d"
      green: "0x98971a"
      yellow: "0xd79921"
      blue: "0x458588"
      magenta: "0xb16286"
      cyan: "0x689d6a"
      white: "0xa89984"

    # Bright colors
    bright:
      black: "0x928374"
      red: "0xfb4934"
      green: "0xb8bb26"
      yellow: "0xfabd2f"
      blue: "0x83a598"
      magenta: "0xd3869b"
      cyan: "0x8ec07c"
      white: "0xebdbb2"

  one_dark: &one_dark # Default colors
    primary:
      background: "0x282c34"
      foreground: "0xabb2bf"

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: "0x282c34"
      cursor: "0xabb2bf"

    # Normal colors
    normal:
      black: "0x282c34"
      red: "0xe06c75"
      green: "0x98c379"
      yellow: "0xe5c07b"
      blue: "0x61afef"
      magenta: "0xc678dd"
      cyan: "0x56b6c2"
      white: "0xabb2bf"

    # Bright colors
    bright:
      black: "0x545862"
      red: "0xe06c75"
      green: "0x98c379"
      yellow: "0xe5c07b"
      blue: "0x61afef"
      magenta: "0xc678dd"
      cyan: "0x56b6c2"
      white: "0xc8ccd4"

    indexed_colors:
      - { index: 16, color: "0xd19a66" }
      - { index: 17, color: "0xbe5046" }
      - { index: 18, color: "0x353b45" }
      - { index: 19, color: "0x3e4451" }
      - { index: 20, color: "0x565c64" }
      - { index: 21, color: "0xb6bdca" }
  # Colors (Ayu Dark)
  ayu_dark: &ayu_dark # Default colors
    primary:
      background: "0x0A0E14"
      foreground: "0xB3B1AD"

    # Normal colors
    normal:
      black: "0x01060E"
      red: "0xEA6C73"
      green: "0x91B362"
      yellow: "0xF9AF4F"
      blue: "0x53BDFA"
      magenta: "0xFAE994"
      cyan: "0x90E1C6"
      white: "0xC7C7C7"

    # Bright colors
    bright:
      black: "0x686868"
      red: "0xF07178"
      green: "0xC2D94C"
      yellow: "0xFFB454"
      blue: "0x59C2FF"
      magenta: "0xFFEE99"
      cyan: "0x95E6CB"
      white: "0xFFFFFF"
# Colors (Ayu Mirage)
  ayu_mirage: &ayu_mirage
    primary:
      background: '#202734'
      foreground: '#CBCCC6'
    normal:
      black:    '#191E2A'
      red:      '#FF3333'
      green:    '#BAE67E'
      yellow:   '#FFA759'
      blue:     '#73D0FF'
      magenta:  '#FFD580'
      cyan:     '#95E6CB'
      white:    '#C7C7C7'

    # Bright colors
    bright:
      black:   '#686868'
      red:     '#F27983'
      green:   '#A6CC70'
      yellow:  '#FFCC66'
      blue:    '#5CCFE6'
      magenta: '#FFEE99'
      cyan:    '#95E6CB'
      white:   '#FFFFFF'

  seoul_256: &seoul_256 # Default colors
    primary:
      background: "#3a3a3a"
      foreground: "#d0d0d0"

    # Normal colors
    normal:
      black: "#4e4e4e"
      red: "#d68787"
      green: "#5f865f"
      yellow: "#d8af5f"
      blue: "#85add4"
      magenta: "#d7afaf"
      cyan: "#87afaf"
      white: "#d0d0d0"
    bright:
      black: "#626262"
      red: "#d75f87"
      green: "#87af87"
      yellow: "#ffd787"
      blue: "#add4fb"
      magenta: "#ffafaf"
      cyan: "#87d7d7"
      white: "#e4e4e4"

  tokyo-night: &tokyo-night
    primary:
      background: "0x1a1b26"
      foreground: "0xa9b1d6"

    # Normal colors
    normal:
      black: "0x32344a"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xad8ee6"
      cyan: "0x449dab"
      white: "0x787c99"

    # Bright colors
    bright:
      black: "0x444b6a"
      red: "0xff7a93"
      green: "0xb9f27c"
      yellow: "0xff9e64"
      blue: "0x7da6ff"
      magenta: "0xbb9af7"
      cyan: "0x0db9d7"
      white: "0xacb0d0"


    nightfox: &nightfox
      # Default colors
      primary:
        background: '0x192330'
        foreground: '0xcdcecf'
      # Normal colors
      normal:
        black:   '0x393b44'
        red:     '0xc94f6d'
        green:   '0x81b29a'
        yellow:  '0xdbc074'
        blue:    '0x719cd6'
        magenta: '0x9d79d6'
        cyan:    '0x63cdcf'
        white:   '0xdfdfe0'
      # Bright colors
      bright:
        black:   '0x475072'
        red:     '0xd6616b'
        green:   '0x58cd8b'
        yellow:  '0xffe37e'
        blue:    '0x84cee4'
        magenta: '0xb8a1e3'
        cyan:    '0x59f0ff'
        white:   '0xf2f2f2'
      indexed_colors:
        - { index: 16, color: '0xf4a261' }
        - { index: 17, color: '0xd67ad2' }


  tokyo-night-storm: &tokyo-night-storm # Default colors
    primary:
      background: "0x24283b"
      foreground: "0xa9b1d6"

    # Normal colors
    normal:
      black: "0x32344a"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xad8ee6"
      cyan: "0x449dab"
      white: "0x9699a8"

    # Bright colors
    bright:
      black: "0x444b6a"
      red: "0xff7a93"
      green: "0xb9f27c"
      yellow: "0xff9e64"
      blue: "0x7da6ff"
      magenta: "0xbb9af7"
      cyan: "0x0db9d7"
      white: "0xacb0d0"
  palenight: &palenight
    # Default colors
    primary:
      background: '0x292d3e'
      foreground: '0xd0d0d0'

    # Normal colors
    normal:
      black:   '0x292d3e'
      red:     '0xf07178'
      green:   '0xc3e88d'
      yellow:  '0xffcb6b'
      blue:    '0x82aaff'
      magenta: '0xc792ea'
      cyan:    '0x89ddff'
      white:   '0xd0d0d0'

    # Bright colors
    bright:
      black:   '0x434758'
      red:     '0xff8b92'
      green:   '0xddffa7'
      yellow:  '0xffe585'
      blue:    '0x9cc4ff'
      magenta: '0xe1acff'
      cyan:    '0xa3f7ff'
      white:   '0xffffff'

        
  rose_pine_moon: &rose_pine_moon
    primary:
      background: '0x232136'
      foreground: '0xe0def4'
    cursor:
      text: '0x232136'
      cursor: '0x825B65'
    vi_mode_cursor:
      text: '0x191724'
      cursor: '0x825B65'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: '0x312E45'
    normal:
      black:   '0x817c9c'
      red:     '0xeb6f92'
      green:   '0x9ccfd8'
      yellow:  '0xf6c177'
      blue:    '0x3e8fb0'
      magenta: '0xc4a7e7'
      cyan:    '0xea9a97'
      white:   '0xe0def4'
    bright:
      black:   '0x6e6a86'
      red:     '0xeb6f92'
      green:   '0x9ccfd8'
      yellow:  '0xf6c177'
      blue:    '0x31748f'
      magenta: '0xc4a7e7'
      cyan:    '0xebbcba'
      white:   '0xe0def4'

colors: *rose_pine_moon
