env:
  TERM: xterm-256color

window:
  padding:
    x: 20
    y: 20

use_thin_strokes: true

font:
  size: 16
  normal:
    family: "FiraCode Nerd Font"
    style: Regular

colors:
  primary:
    background: "#16161e"
    foreground: "#C5C8C6"

  normal:
    black: "#282a2e"
    red: "#CC6666"
    green: "#B5BD68"
    yellow: "#F0C674"
    cyan: "#8ABEB7"
    magenta: "#B294BB"
    blue: "#81A2BE"
    white: "#C5C8C6"

  bright:
    black: "#383A3E"
    red: "#A54242"
    green: "#8C9440"
    yellow: "#DE935F"
    cyan: "#5E8D87"
    magenta: "#85678F"
    blue: "#5F819D"
    white: "#c1c0c0"
