window:
  decorations: "none"
  padding:
    x: 10
    y: 10

font:
  normal:
    # family: "SauceCodePro Nerd Font"
    family: "FiraCode Nerd Font Mono"
    style: Regular
  size: 17

schemes:
  everforest_dark_hard: &everforest_dark_hard
    primary:
      background: "#2b3339"
      foreground: "#d3c6aa"
    normal:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
    bright:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
  everforest_dark_medium: &everforest_dark_medium
    primary:
      background: "#2f383e"
      foreground: "#d3c6aa"
    normal:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
    bright:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
  everforest_dark_soft: &everforest_dark_soft
    primary:
      background: "#323d43"
      foreground: "#d3c6aa"
    normal:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
    bright:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"
  gruvbox: &gruvbox
    primary:
      # hard contrast:
      background: "0x1d2021"
      # background: '0x282828'
      # soft contrast: background = '0x32302f'
      foreground: "0xebdbb2"

    # Normal colors
    normal:
      black: "0x282828"
      red: "0xcc241d"
      green: "0x98971a"
      yellow: "0xd79921"
      blue: "0x458588"
      magenta: "0xb16286"
      cyan: "0x689d6a"
      white: "0xa89984"

    # Bright colors
    bright:
      black: "0x928374"
      red: "0xfb4934"
      green: "0xb8bb26"
      yellow: "0xfabd2f"
      blue: "0x83a598"
      magenta: "0xd3869b"
      cyan: "0x8ec07c"
      white: "0xebdbb2"
  one_dark: &one_dark # Default colors
    primary:
      background: "0x282c34"
      foreground: "0xabb2bf"

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: "0x282c34"
      cursor: "0xabb2bf"

    # Normal colors
    normal:
      black: "0x282c34"
      red: "0xe06c75"
      green: "0x98c379"
      yellow: "0xe5c07b"
      blue: "0x61afef"
      magenta: "0xc678dd"
      cyan: "0x56b6c2"
      white: "0xabb2bf"

    # Bright colors
    bright:
      black: "0x545862"
      red: "0xe06c75"
      green: "0x98c379"
      yellow: "0xe5c07b"
      blue: "0x61afef"
      magenta: "0xc678dd"
      cyan: "0x56b6c2"
      white: "0xc8ccd4"

    indexed_colors:
      - { index: 16, color: "0xd19a66" }
      - { index: 17, color: "0xbe5046" }
      - { index: 18, color: "0x353b45" }
      - { index: 19, color: "0x3e4451" }
      - { index: 20, color: "0x565c64" }
      - { index: 21, color: "0xb6bdca" }
  # Colors (Ayu Dark)
  ayu_dark: &ayu_dark # Default colors
    primary:
      background: "0x0A0E14"
      foreground: "0xB3B1AD"

    # Normal colors
    normal:
      black: "0x01060E"
      red: "0xEA6C73"
      green: "0x91B362"
      yellow: "0xF9AF4F"
      blue: "0x53BDFA"
      magenta: "0xFAE994"
      cyan: "0x90E1C6"
      white: "0xC7C7C7"

    # Bright colors
    bright:
      black: "0x686868"
      red: "0xF07178"
      green: "0xC2D94C"
      yellow: "0xFFB454"
      blue: "0x59C2FF"
      magenta: "0xFFEE99"
      cyan: "0x95E6CB"
      white: "0xFFFFFF"

  seoul_256: &seoul_256 # Default colors
    primary:
      background: "#3a3a3a"
      foreground: "#d0d0d0"

    # Normal colors
    normal:
      black: "#4e4e4e"
      red: "#d68787"
      green: "#5f865f"
      yellow: "#d8af5f"
      blue: "#85add4"
      magenta: "#d7afaf"
      cyan: "#87afaf"
      white: "#d0d0d0"
    bright:
      black: "#626262"
      red: "#d75f87"
      green: "#87af87"
      yellow: "#ffd787"
      blue: "#add4fb"
      magenta: "#ffafaf"
      cyan: "#87d7d7"
      white: "#e4e4e4"
  tokyo-night: &tokyo-night
    primary:
      background: "0x1a1b26"
      foreground: "0xa9b1d6"

    # Normal colors
    normal:
      black: "0x32344a"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xad8ee6"
      cyan: "0x449dab"
      white: "0x787c99"

    # Bright colors
    bright:
      black: "0x444b6a"
      red: "0xff7a93"
      green: "0xb9f27c"
      yellow: "0xff9e64"
      blue: "0x7da6ff"
      magenta: "0xbb9af7"
      cyan: "0x0db9d7"
      white: "0xacb0d0"

  tokyo-night-storm: &tokyo-night-storm # Default colors
    primary:
      background: "0x24283b"
      foreground: "0xa9b1d6"

    # Normal colors
    normal:
      black: "0x32344a"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xad8ee6"
      cyan: "0x449dab"
      white: "0x9699a8"

    # Bright colors
    bright:
      black: "0x444b6a"
      red: "0xff7a93"
      green: "0xb9f27c"
      yellow: "0xff9e64"
      blue: "0x7da6ff"
      magenta: "0xbb9af7"
      cyan: "0x0db9d7"
      white: "0xacb0d0"

colors: *gruvbox
