window:
  # Full for MacOS
  decorations: 'full'
  # None for PopOS
  # decorations: 'none'
  padding:
    x: 10 
    y: 10

font:
  normal:
    family: 'Dank Mono'
    style: 'Regular'

  # normal screen
  # size: 13
  # retina display
  size: 15

# # Colors (Gruvbox dark)
# colors:
#   # Default colors
#   primary:
#     # hard contrast:
#     background:   '0x1d2021'
#     # background: '0x282828'
#     # soft contrast: background = '0x32302f'
#     foreground: '0xebdbb2'

#   # Normal colors
#   normal:
#     black:   '0x282828'
#     red:     '0xcc241d'
#     green:   '0x98971a'
#     yellow:  '0xd79921'
#     blue:    '0x458588'
#     magenta: '0xb16286'
#     cyan:    '0x689d6a'
#     white:   '0xa89984'

#   # Bright colors
#   bright:
#     black:   '0x928374'
#     red:     '0xfb4934'
#     green:   '0xb8bb26'
#     yellow:  '0xfabd2f'
#     blue:    '0x83a598'
#     magenta: '0xd3869b'
#     cyan:    '0x8ec07c'
#     white:   '0xebdbb2'

  
# Colors (Ayu Dark)
colors:
  # Default colors
  primary:
    background: '0x0A0E14'
    foreground: '0xB3B1AD'

  # Normal colors
  normal:
    black:   '0x01060E'
    red:     '0xEA6C73'
    green:   '0x91B362'
    yellow:  '0xF9AF4F'
    blue:    '0x53BDFA'
    magenta: '0xFAE994'
    cyan:    '0x90E1C6'
    white:   '0xC7C7C7'

  # Bright colors
  bright:
    black:   '0x686868'
    red:     '0xF07178'
    green:   '0xC2D94C'
    yellow:  '0xFFB454'
    blue:    '0x59C2FF'
    magenta: '0xFFEE99'
    cyan:    '0x95E6CB'
    white:   '0xFFFFFF'
