#!/bin/bash

config_dir=~/configs

# 1. First you check if a tmux session exists with a given name.
tmux has-session -t=configs 2> /dev/null

# 2. Create the session if it doesn't exists.
if [[ $? -ne 0 ]]; then
  TMUX='' tmux new-session -d -s configs -c ~/configs
fi

# 3. Attach if outside of tmux, switch if you're in tmux.
if [[ -z "$TMUX" ]]; then
  tmux attach -t configs
else
  tmux switch-client -t configs
fi
